// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class AngularResourceService : AngularResourceServiceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(" \r\nvar app = angular.module(\"challenge\", [ \"ngResource\"]); \r\n");
            
            #line 3 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
     
    var controllers = GetControllers(); 
    foreach(var controller in controllers) 
    { 
        var className = controller.Identifier.Text.Replace("Controller", ""); 

            
            #line default
            #line hidden
            this.Write("      app.factory(");
            
            #line 8 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("Resource , function ($resource) { \r\n            return $resource(\'");
            
            #line 9 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Url));
            
            #line default
            #line hidden
            this.Write("api/");
            
            #line 9 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\',{");
            
            #line 9 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" : \'@");
            
            #line 9 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\'},{ \r\n");
            
            #line 10 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
 
        var models= GetModels(controller); 
        var properties = GetProperties(models); 
        foreach (var property in properties) 
        { 

            
            #line default
            #line hidden
            this.Write(" \r\n            ");
            
            #line 16 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" : \"\", \r\n");
            
            #line 17 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
 
        } 
        var actions = GetActions(controller); 
        foreach (var action in actions) 
        { 
            if (action == "query") 
            { 

            
            #line default
            #line hidden
            this.Write("         query : { \r\n              method: \"GET\"     \r\n            , isArray : tr" +
                    "ue \r\n             } \r\n");
            
            #line 28 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            } 
            else{ 

            
            #line default
            #line hidden
            this.Write("     , ");
            
            #line 30 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action));
            
            #line default
            #line hidden
            this.Write(": { \r\n               method: \"");
            
            #line 31 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.ToUpper()));
            
            #line default
            #line hidden
            this.Write("\" \r\n            }         \r\n");
            
            #line 33 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
            } 
        } 

            
            #line default
            #line hidden
            this.Write(" \r\n   }); \r\n}); \r\n");
            
            #line 38 "C:\Users\nharr\Source\Workspaces\MyFirstProject\RoslynPlayground\RoslynPlayground\T4\AngularResourceService.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write(" ");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
